import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    maxWidth: 400,
    alignSelf: 'center',
    backgroundColor: '#F9FAFB',
    width: '100%',
  },
  header: {
    backgroundColor: '#4F46E5',
    paddingTop: 40,
    paddingBottom: 16,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  headerSubtitle: {
    color: '#A5B4FC',
    fontSize: 14,
  },
  profileButton: {
    width: 40,
    height: 40,
    backgroundColor: '#FFFFFF',
    borderRadius: 9999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollArea: {
    flex: 1,
    padding: 16,
    paddingTop: 16,
  },
  sectionTitle: {
    color: '#1F2937',
    fontSize: 18,
    fontWeight: 'bold',
    paddingHorizontal: 8,
    marginBottom: 12,
  },
  listContainer: {
    gap: 12,
  },
  listItem: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  itemIcon: {
    width: 48,
    height: 48,
    backgroundColor: '#E5E7EB',
    borderRadius: 9999,
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  itemTextContainer: {
    flex: 1,
    minWidth: 0,
  },
  itemTitle: {
    fontSize: 16,
    fontWeight: '600',
  },
  itemSubtitle: {
    fontSize: 14,
    color: '#6B7280',
  },
  itemViewButton: {
    fontSize: 14,
    color: '#4F46E5',
    marginLeft: 16,
    flexShrink: 0,
  },
  bottomSpacer: {
    height: 64,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 10,
  },
  tabItem: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 8,
  },
  tabIcon: {
    fontSize: 24,
  },
  tabLabel: {
    fontSize: 12,
    fontWeight: '500',
  },
  tabLabelActive: {
    color: '#4F46E5',
  },
  tabLabelInactive: {
    color: '#6B7280',
  },
  lockInButton: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 8,
    fontSize: 24,
    backgroundColor: '#333333',
    color: '#DDDDDD',
    borderRadius: 9,
    padding: 5,
  },
  formContainer: {
    marginTop: 20,
    padding: 16,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginBottom: 20,
    color: '#1F2937',
  },
  inputButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    padding: 12,
    marginBottom: 20,
    justifyContent: 'center',
  },
  inputText: {
    fontSize: 16,
    color: '#1F2937',
  },
  inputPlaceholder: {
    fontSize: 16,
    color: '#9CA3AF',
  },
  createButton: {
    backgroundColor: '#4F46E5',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 20,
    shadowColor: '#4F46E5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 4,
  },
  createButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  container_li: {
    flex: 1,
    padding: 24,
    backgroundColor: '#1F2937',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusText_li: {
    fontSize: 44,
    fontWeight: 'bold',
    color: '#AAAAAA',
    marginBottom: 60,
    letterSpacing: 2,
  },
  timerText_li: {
    fontSize: 72,
    fontWeight: '900',
    color: '#ECF0F1',
    marginBottom: 10,
  },
  assignmentNameText_li: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#9CA3AF',
    marginBottom: 30,
    textAlign: 'center',
  },
  assignmentIdText_li: {
    fontSize: 14,
    color: '#4B5563',
    position: 'absolute',
    bottom: 10,
    opacity: 0.5,
  },
  exitButton_li: {
    marginTop: 60,
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  exitButtonText_li: {
    color: '#000000',
    fontWeight: 'bold',
    fontSize: 22,
  },
  trophySelect:{
    width: 110,
    height: 140,
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 5,
    fontSize: 17,
    backgroundColor: '#333333',
    color: '#DDDDDD',
    borderRadius: 9,
    padding: 5,
  },
  lockSelect:{
    width: 165,
    height: 230,
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 5,
    fontSize: 17,
    backgroundColor: '#EEEEEE',
    borderRadius: 9,
    padding: 5,
    shadowColor: "#000",
    shadowOffset: { width: 16, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  achievementText:{
    fontSize: 25,
    alignItems: 'center',
    flexDirection: 'column',
    color: '#24252C',
  },
  listContainer2: {
    gap: 30,
  },
  // --- NEW SELECTION BUTTON STYLES ---
  selectionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    gap: 8,
  },
  optionButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
  },
  optionButtonActive: {
    backgroundColor: '#4F46E5',
    borderColor: '#4F46E5',
  },
  optionText: {
    fontSize: 14,
    color: '#374151',
    fontWeight: '500',
    textAlign: 'center',
  },
  optionTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  }
});

export default styles;